# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d55c14257aa2a56109957281316cbee384a8dae3fa61c279e9e76057d96aacd3984675f9c3cc21f328308a0d7480619d35d6c552a9d8a5147732e997977dc0e

test:
  secret_key_base: a7a95a8395013d20a30554a267f3324920cb9e31566139e4d1c1fbbbb916e2c4efc6c54ffcac3123b86ffb7dcac2cfb618af506cd1e5aaf40ec3cc736ce6b646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: e2e5f8b1b5223a9348ec786b8f5b2598c3dc3dc3761e83bd33082b9466bf211a0159417a86f387831c204480a9f4b0234cb0e9e71809316f584b0a24f4b86054
